version: '3.9'
services:
  fastapi:
    image: fastapi-docker:initial-app
    container_name: fastapi-app
    volumes:
      - .:/home/fastapi
    ports:
      - 8000:8000
    command:
      - /bin/bash
      - -c
      - |
        chmod +x start.sh
        ./start.sh
